services:
  api:
    container_name: "it-hero-map-api"
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - it-hero-map-network
  
  db:
    container_name: "it-hero-map-db"
    image: postgres:17
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - it-hero-map-network

networks:
  it-hero-map-network:
    driver: bridge
